
class Keys:
    CUSTOMER_ID = "customer_id"
    ITEMS = "items"
    PRODUCT_CODE = "product_code"
    QUANTITY = "quantity"
    PRICE = "price"
    ORDER_DATE = "order_date"
    PAYMENT_INFO = "payment_info"
    PAYMENT_METHOD = "payment_method"
    TYPE = "type"
    CARD = "card"
    NUMBER = "number"
    EXPIRY_MONTH = "expiry_month"
    EXPIRY_YEAR = "expiry_year"
    CVC = "cvc"
    BILLING_ADDRESS = "billing_address"
    FIRST_NAME = "first_name"
    LAST_NAME = "last_name"
    HOUSE_NUMBER = "house_number"
    STREET_NAME = "street_name"
    ADDRESS_LINE_1 = "address_line_1"
    ADDRESS_LINE_2 = "address_line_2"
    CITY = "city"
    POST_CODE = "post_code"
    COUNTRY = "country"
    SHIPPING_ADDRESS = "shipping_address"
    